development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: talk_to_me_dev

test:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: talk_to_me_test

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: talk_to_me_production
